<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <base href="<?=LIMB_HTTP_BASE_PATH?>" />  
  <script type="text/javascript">
    window.myjs = window.myjs || {}; 
    window.myjs.server_vars = <?=json_encode($this->toolkit->getJsVars())?>;
    var project_id = {$#project_id}+1*0;  
  </script>  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" type="text/javascript"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js" type="text/javascript"></script>    
  
  {{file_versions_to_js js_var="ammo.file_versions" /}}  
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/themes/smoothness/jquery-ui.css"></style>
  {{css_compiled src="styles/bootstrap.min.css" dir="media/var/css" /}}
  {{css_compiled src="styles/bootstrap-responsive.min.css" dir="media/var/css" /}}  
  {{css_compiled src="styles/jquery.dataTables.css" dir="media/var/css" /}}
  {{css_compiled src="styles/main.css" dir="media/var/css" /}}
  {{css_compiled src="styles/filter.css" dir="media/var/css" /}}
  {{css_compiled src="styles/datepicker.css" dir="media/var/css" /}}
  {{slot id="head" /}}    
  
  {{js_combined dir="media/var/js/"}}
    {{js_once src="js/bootstrap.min.js" /}}
    {{js_once src="js/main.js" /}}  
    {{js_once src="js/jquery.dataTables.min.js" /}}
    {{js_once src="js/chart.js" /}}
    {{js_once src="js/filter.js" /}}
    {{js_once src="js/time_control.js" /}}
    {{js_once src="js/highcharts.js" /}}    
    {{js_once src="js/datepicker.js" /}}
    {{js_once src="js/jquery.jeditable.mini.js" /}}
    {{slot id="js_include" /}}
  {{/js_combined}}
  
</head>
  <body>    
    <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="">Stats</a>
        <div class="nav-collapse collapse">
          <ul class="nav">
            
            
          </ul>          
          <ul class="nav pull-right">
            <li class="dropdown">              
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="time-button">Время<b class="caret"></b></a>                
                <ul class="dropdown-menu" role="menu" aria-labelledby="time-filter" id="time-filter">
                  <li>
                      <a href="#" onclick="return window.timeController.selectPeriod(this);">
                        <input type="radio" name="optionsRadios" id="time-week" value="time-week" style="margin-right: 10px;margin-top: -2px;"/>Неделя
                      </a>
                  </li>                  
                  <li>
                      <a href="#" onclick="return window.timeController.selectPeriod(this);">
                        <input type="radio" name="optionsRadios" id="time-mounth" value="time-mounth" style="margin-right: 10px;margin-top: -2px;" checked/>Месяц
                      </a>
                  </li>                  
                  <li>
                      <a href="#" onclick="return window.timeController.selectPeriod(this);">
                        <input type="radio" name="optionsRadios" id="time-2mounth" value="time-2mounth" style="margin-right: 10px;margin-top: -2px;"/>Все время
                      </a>
                  </li>                  
                  <li>
                      <a href="#" onclick="return window.timeController.selectPeriod(this);">
                        <input type="radio" name="optionsRadios" id="time-custom" value="time-custom" style="margin-right: 10px;margin-top: -2px;"/>Настроить                      
                      </a>
                        <div style="margin-left: 20px;" class="time-text">
                          <ul style="list-style: none;padding-right: 10px; padding-bottom: 10px;" >
                            <li><span style="float: left; margin-top: 12px;">Начало: </span>   <input class="btn" type="button" id="time-custom-start" value="time-custom-start" style="float: right;"/></li>
                            <li><span style="float: left; margin-top: 12px;">Окончание: </span><input class="btn" type="button" id="time-custom-stop"  value="time-custom-stop"  style="float: right;"/></li>
                          </ul>
                        </div>                    
                  </li>
                  <li><a href="" role="button" class="btn" data-toggle="modal" onclick="return window.timeController.applyPeriod();">Изменить</a></li>
                </ul>                
            </li>            
            <li class="dropdown">              
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="filter-button">Фильтр: Все <b class="caret"></b></a>                
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel" id="filter-dropdown">
                  {{list using="$#filters" as="$item"}}
                    {{list:item}}
                    <li>
                      <a href="#" onclick="return window.filter.setup({$item.data},this);">
                        <input type="radio" name="optionsRadios" id="{$item.name}" value="{$item.name}" style="margin-right: 10px;margin-top: -2px;"/>{$item.name}
                      </a>
                    </li>
                    {{/list:item}}
                  {{/list}}
                  <li>
                      <a href="#" onclick="return window.filter.setup({},this);">
                        <input type="radio" name="optionsRadios" id="all" value="all" style="margin-right: 10px;margin-top: -2px;"/>Все
                      </a>
                  </li>
                  <li><a href="" role="button" class="btn" data-toggle="modal" onclick="return window.filter.show();">Изменить</a></li>
                </ul>                
            </li>              
            <li>
              <a href="login/logout">{$#exit}</a>            
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
  
<div id="content">
  {{slot id="content_wrapper" /}}
</div>
    
<div id="filter" class="modal hide fade" data-show="false">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Фильтр</h3><span>Имя: </span><input style = "margin-top: 5px;" type="text" name="name" style="width: 40%;"/>
  </div>
  <div class="modal-body" style="height: 800px">    
    <table style="width:100%">
    </table>
  </div>
  <div class="modal-footer">
    <a id="filter-apply" href="#" class="btn btn-primary"          onclick="return window.filter.apply(this);">Apply</a>
    <a id="filter-save"  href="#" class="btn btn-primary disabled" onclick="return window.filter.save(this);">Save filter</a>
  </div>
</div>    

<div class="ajax-loader" style="display: none;">&nbsp;</div>

  <script type="text/javascript">
    jQuery(document).ready(function() {
      $('#filter').modal({show:false});
      period = window.timeController.getPeriod();      
      $('#time-custom-start').val($.datepicker.formatDate('yy-mm-dd', new Date(period.bday*1000)));      
      $('#time-custom-stop').val($.datepicker.formatDate('yy-mm-dd', new Date(period.eday*1000)));      
      
      $('#time-custom-stop').DatePicker({
        date: (new Date(period.eday*1000)),
        current: (new Date(period.eday*1000)),
        flat: false,
        calendars: 1,        
        position: 'right',        
        onChange: function(formated, dates){
          $('#time-custom-stop').val(formated);        
          $('#time-custom-stop').DatePickerHide(); 
          window.timeController.changeStop(dates);
        },
      });
      
      $('#time-custom-start').DatePicker({
        date: (new Date(period.bday*1000)),
        current: (new Date(period.bday*1000)),
        flat: false,
        calendars: 1,        
        position: 'right',
        onChange: function(formated, dates){
          $('#time-custom-start').val(formated);        
          $('#time-custom-start').DatePickerHide();        
          window.timeController.changeStart(dates);
        },
      });
      
      window.timeController.updateHeader();
      
      {{aslot id='js_ready'/}}      
    });
  </script>
  
</body>
  
</html>
