<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <base href="<?=LIMB_HTTP_BASE_PATH?>" />  
  <script type="text/javascript">
    window.myjs = window.myjs || {}; 
    window.myjs.server_vars = <?=json_encode($this->toolkit->getJsVars())?>;
    var project_id = {$#project_id}+1*0;  
  </script>  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" type="text/javascript"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js" type="text/javascript"></script>    
  
  {{file_versions_to_js js_var="ammo.file_versions" /}}  
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/themes/smoothness/jquery-ui.css"></style>
  {{css_compiled src="styles/bootstrap.min.css" dir="media/var/css" /}}
  {{css_compiled src="styles/bootstrap-responsive.min.css" dir="media/var/css" /}}  
  {{css_compiled src="styles/jquery.dataTables.css" dir="media/var/css" /}}
  {{css_compiled src="styles/main.css" dir="media/var/css" /}}
  {{css_compiled src="styles/datepicker.css" dir="media/var/css" /}}
  {{slot id="head" /}}    
  
  {{js_combined dir="media/var/js/"}}
    {{js_once src="js/bootstrap.min.js" /}}
    {{js_once src="js/main.js" /}}  
    {{js_once src="js/jquery.dataTables.min.js" /}}
    {{js_once src="js/chart.js" /}}
    {{js_once src="js/highcharts.js" /}}    
    {{js_once src="js/datepicker.js" /}}
    {{js_once src="js/jquery.jeditable.mini.js" /}}
    <!--
    j123s_once src="js/jquery.hashchange.min.js" /}}
    j123s_once src="js/jquery.easytabs.min.js" /}}            
    j123s_once src="js/exporting.js" /}}    
    -->    
    {{slot id="js_include" /}}
  {{/js_combined}}
  
</head>
  <body>    
    <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="">Stats</a>
        <div class="nav-collapse collapse">
          <ul class="nav">
            
            
          </ul>
          <ul class="nav pull-right">
            <li>
              <a href="login/logout">{$#exit}</a>            
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
  
<div id="content">
  {{slot id="content_wrapper" /}}
</div>

<div class="ajax-loader" style="display: none;">&nbsp;</div>

  <script type="text/javascript">
    jQuery(document).ready(function() {  
      {{aslot id='js_ready'/}}
    });
  </script>
  
</body>
  
</html>
