<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <base href="<?=LIMB_HTTP_BASE_PATH?>" />  
  <script type="text/javascript">
    window.myjs = window.myjs || {}; 
    window.myjs.server_vars = <?=json_encode($this->toolkit->getJsVars())?>
  </script>  
  {{file_versions_to_js js_var="ammo.file_versions" /}}  
  <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/themes/smoothness/jquery-ui.css"></style>
  {{css_compiled src="styles/main.css" dir="media/var/css" /}}  
  {{css_compiled src="styles/tabs.css" dir="media/var/css" /}}
  {{css_compiled src="styles/datepicker.css" dir="media/var/css" /}}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" type="text/javascript"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js" type="text/javascript"></script>    
  {{slot id="head" /}}    
  {{js_combined dir="media/var/js/"}}
    {{js_once src="js/datepicker.js" /}}
    {{js_once src="js/jquery.hashchange.min.js" /}}
    {{js_once src="js/jquery.easytabs.min.js" /}}    
    {{js_once src="js/highcharts.js" /}}    
    {{js_once src="js/exporting.js" /}}    
  {{/js_combined}}
  <script>
    var project_id = {$#project_id};
  </script>
</head>
<body>
<center>
{{slot id="menu" /}}
{{slot id="content_wrapper" /}}
</center>

{{js:i18n_dictonary dir="media/var/i18n/" js_var="ammo.i18n_dictonary" /}}
{{js_combined dir="media/var/js/"}}  
  {{js_once src="js/main.js" /}}  
  {{js_once src="js/chart.js" /}}
{{/js_combined}}

<div class="ajax-loader" style="display: none;">&nbsp;</div>
{{slot id="js_include" /}}
<script type="text/javascript">
jQuery(document).ready(function() {  
  {{aslot id='js_ready'/}}
});
</script>
</html>
