<table style="width: 100%;height: 100%;" id="filter-param">
  <thead>
    <tr>
      <th style="width: 25%;">Параметр</th><th style="width: 25%;">Операция</th><th style="width: 25%;">Значение</th><th style="width: 25%;">Отношение</th>          
    </tr>
  </thead>
  <tbody>
    <tr name="item_id">
      <td>ID ассета</td>
      <td><select><option value="-">-</option><option value="=">=</option> <option value=">">></option><option value=">=">>=</option><option value="<="><=</option><option value="<">><</option><option value="!=">!=</option><option value="LIKE">LIKE</option><option value="BETWEEN">BETWEEN</option></select></td>
      <td><input type="text"/></td>
      <td><select  style="width: 150px;"><option value="-"> </option><option value="and">AND</option><option value="or">OR</option></select></td>
    </tr>
    <tr name="level">
      <td>Уровень</td>
      <td><select><option value="-">-</option><option value="=">=</option> <option value=">">></option><option value=">=">>=</option><option value="<="><=</option><option value="<">><</option><option value="!=">!=</option><option value="LIKE">LIKE</option><option value="BETWEEN">BETWEEN</option></select></td>
      <td><input type="text"/></td>
      <td><select  style="width: 150px;"><option value="-"> </option><option value="and">AND</option><option value="or">OR</option></select></td>
    </tr>
    <tr name="energy">
      <td>Энергия</td>
      <td><select><option value="-">-</option><option value="=">=</option> <option value=">">></option><option value=">=">>=</option><option value="<="><=</option><option value="<">><</option><option value="!=">!=</option><option value="LIKE">LIKE</option><option value="BETWEEN">BETWEEN</option></select></td>
      <td><input type="text"/></td>
      <td><select  style="width: 150px;"><option value="-"> </option><option value="and">AND</option><option value="or">OR</option></select></td>
    </tr>
    <tr name="real">
      <td>Реал</td>
      <td><select><option value="-">-</option><option value="=">=</option> <option value=">">></option><option value=">=">>=</option><option value="<="><=</option><option value="<">><</option><option value="!=">!=</option><option value="LIKE">LIKE</option><option value="BETWEEN">BETWEEN</option></select></td>
      <td><input type="text"/></td>
      <td><select  style="width: 150px;"><option value="-"> </option><option value="and">AND</option><option value="or">OR</option></select></td>
    </tr>
    <tr name="bonus">
      <td>Бонус</td>
      <td><select><option value="-">-</option><option value="=">=</option> <option value=">">></option><option value=">=">>=</option><option value="<="><=</option><option value="<">><</option><option value="!=">!=</option><option value="LIKE">LIKE</option><option value="BETWEEN">BETWEEN</option></select></td>
      <td><input type="text"/></td>
      <td><select  style="width: 150px;"><option value="-"> </option><option value="and">AND</option><option value="or">OR</option></select></td>
    </tr>
    <tr name="money">
      <td>Валюта приложения</td>
      <td><select><option value="-">-</option><option value="=">=</option> <option value=">">></option><option value=">=">>=</option><option value="<="><=</option><option value="<">><</option><option value="!=">!=</option><option value="LIKE">LIKE</option><option value="BETWEEN">BETWEEN</option></select></td>
      <td><input type="text"/></td>
      <td><select  style="width: 150px;"><option value="-"> </option><option value="and">AND</option><option value="or">OR</option></select></td>
    </tr>
    <tr name="referal">
      <td>Реферал</td>
      <td><select><option value="-">-</option><option value="=">=</option> <option value=">">></option><option value=">=">>=</option><option value="<="><=</option><option value="<">><</option><option value="!=">!=</option><option value="LIKE">LIKE</option><option value="BETWEEN">BETWEEN</option></select></td>
      <td><input type="text"/></td>
      <td><select  style="width: 150px;"><option value="-"> </option><option value="and">AND</option><option value="or">OR</option></select></td>
    </tr>
    <tr name ="reg_time">
      <td>Дата регистрации</td>
      <td><select><option value="-">-</option><option value="BETWEEN">BETWEEN</option></select></td>
      <td><input type="text"/></td>
      <td><select  style="width: 150px;"><option value="-"> </option><option value="and">AND</option><option value="or">OR</option></select></td>
    </tr>
  </tbody>
</table>