<table style="width: 100%;" id="filter-param">
  <tbody>
    <tr><td>
      <div class="btn-group">
        <button name ="btn_name" btn_id ="-1" class="btn dropdown-toggle" data-toggle="dropdown">Поле</button>
        <button class="btn dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>                  
        <ul class="dropdown-menu">
          <li><a href="#" btn_id="item_id"  onclick="return window.filter.changeColumn(this);">ID ассета         </a></li>
          <li><a href="#" btn_id="level"    onclick="return window.filter.changeColumn(this);">Уровень           </a></li>
          <li><a href="#" btn_id="energy"   onclick="return window.filter.changeColumn(this);">Энергия           </a></li>
          <li><a href="#" btn_id="real"     onclick="return window.filter.changeColumn(this);">Реал              </a></li>
          <li><a href="#" btn_id="bonus"    onclick="return window.filter.changeColumn(this);">Бонус             </a></li>
          <li><a href="#" btn_id="money"    onclick="return window.filter.changeColumn(this);">Валюта приложения </a></li>
          <li><a href="#" btn_id="referal"  onclick="return window.filter.changeColumn(this);">Реферал           </a></li>
          <li><a href="#" btn_id="reg_time" onclick="return window.filter.changeColumn(this);">Дата регистрации  </a></li>          
        </ul>
      </div>
      <div class="btn-group">  
        <button name ="btn_name" btn_id ="-1" class="btn dropdown-toggle" data-toggle="dropdown">Действие</button>
        <button class="btn dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>                  
        <ul class="dropdown-menu">
          <li><a href="#" btn_id=">"     onclick="return window.filter.changeColumn(this);">> </a></li>
          <li><a href="#" btn_id=">="    onclick="return window.filter.changeColumn(this);">>=</a></li>
          <li><a href="#" btn_id="<="    onclick="return window.filter.changeColumn(this);"><=</a></li>
          <li><a href="#" btn_id="<"     onclick="return window.filter.changeColumn(this);">< </a></li>
          <li><a href="#" btn_id="!="    onclick="return window.filter.changeColumn(this);">!=</a></li>
          <li><a href="#" btn_id="IN"    onclick="return window.filter.changeColumn(this);">IN</a></li>
          <li><a href="#" btn_id="LIKE"  onclick="return window.filter.changeColumn(this);">LIKE</a></li>          
        </ul>
      </div>
        <input class="input-medium" type="text" value="-" style="margin-top: 10px;width: 450px;"/>
    </td></tr>
    <tr>
      <td>
        <input type="button" class="btn btn-primary" value="Добавить строку" onclick="return window.filter.addRule(this);"/>
      </td>     
    </tr>
<!--    <tr name="item_id">
      <td>ID ассета</td>
      <td><select><option value="-">-</option><option value="=">=</option> <option value=">">></option><option value=">=">>=</option><option value="<="><=</option><option value="<">><</option><option value="!=">!=</option><option value="LIKE">LIKE</option><option value="BETWEEN">BETWEEN</option><option value="IN">IN</option></select></td>
      <td><input type="text" style="float:left;margin-right: -35px"/><button class="btn dropdown-toggle" style="float:left;" onclick=" if($('#item_id-selector').css('display')=='block') $('#item_id-selector').css('display','none'); else $('#item_id-selector').css('display','block');"><span class="caret"></span></button>
        <div id="item_id-selector" style="width: 550px; left:-250px; position: relative; background-color: #999; height:200px; display: block;border: 1px solid #000; margin-top: 40px; display: none; overflow-y: scroll">
          <table>
            <tr>
              <th style="width: 30%;border-right: 1px solid #000">ID</th>
              <th>FILE</th>
            </tr>
            {{list using="$#keys" as="$item"}}
              {{list:item}}
              <tr>
                <td style="text-align: left;border-right: 1px solid #000">{$item.id}</td>
                <td style="text-align: left">{$item.file}</td>
              </tr>                
              {{/list:item}}
            {{/list}}     
          </table>
        </div>
      </td>
      <td><select  style="width: 150px;"><option value="-"> </option><option value="and">AND</option><option value="or">OR</option></select></td>
    </tr>
    <tr name="level">
      <td>Уровень</td>
      <td><select><option value="-">-</option><option value="=">=</option> <option value=">">></option><option value=">=">>=</option><option value="<="><=</option><option value="<">><</option><option value="!=">!=</option><option value="LIKE">LIKE</option><option value="BETWEEN">BETWEEN</option></select></td>
      <td><input type="text"/></td>
      <td><select  style="width: 150px;"><option value="-"> </option><option value="and">AND</option><option value="or">OR</option></select></td>
    </tr>
    <tr name="energy">
      <td>Энергия</td>
      <td><select><option value="-">-</option><option value="=">=</option> <option value=">">></option><option value=">=">>=</option><option value="<="><=</option><option value="<">><</option><option value="!=">!=</option><option value="LIKE">LIKE</option><option value="BETWEEN">BETWEEN</option></select></td>
      <td><input type="text"/></td>
      <td><select  style="width: 150px;"><option value="-"> </option><option value="and">AND</option><option value="or">OR</option></select></td>
    </tr>
    <tr name="real">
      <td>Реал</td>
      <td><select><option value="-">-</option><option value="=">=</option> <option value=">">></option><option value=">=">>=</option><option value="<="><=</option><option value="<">><</option><option value="!=">!=</option><option value="LIKE">LIKE</option><option value="BETWEEN">BETWEEN</option></select></td>
      <td><input type="text"/></td>
      <td><select  style="width: 150px;"><option value="-"> </option><option value="and">AND</option><option value="or">OR</option></select></td>
    </tr>
    <tr name="bonus">
      <td>Бонус</td>
      <td><select><option value="-">-</option><option value="=">=</option> <option value=">">></option><option value=">=">>=</option><option value="<="><=</option><option value="<">><</option><option value="!=">!=</option><option value="LIKE">LIKE</option><option value="BETWEEN">BETWEEN</option></select></td>
      <td><input type="text"/></td>
      <td><select  style="width: 150px;"><option value="-"> </option><option value="and">AND</option><option value="or">OR</option></select></td>
    </tr>
    <tr name="money">
      <td>Валюта приложения</td>
      <td><select><option value="-">-</option><option value="=">=</option> <option value=">">></option><option value=">=">>=</option><option value="<="><=</option><option value="<">><</option><option value="!=">!=</option><option value="LIKE">LIKE</option><option value="BETWEEN">BETWEEN</option></select></td>
      <td><input type="text"/></td>
      <td><select  style="width: 150px;"><option value="-"> </option><option value="and">AND</option><option value="or">OR</option></select></td>
    </tr>
    <tr name="referal">
      <td>Реферал</td>
      <td><select><option value="-">-</option><option value="=">=</option> <option value=">">></option><option value=">=">>=</option><option value="<="><=</option><option value="<">><</option><option value="!=">!=</option><option value="LIKE">LIKE</option><option value="BETWEEN">BETWEEN</option></select></td>
      <td><input type="text"/></td>
      <td><select  style="width: 150px;"><option value="-"> </option><option value="and">AND</option><option value="or">OR</option></select></td>
    </tr>
    <tr name ="reg_time">
      <td>Дата регистрации</td>
      <td><select><option value="-">-</option><option value="BETWEEN">BETWEEN</option></select></td>
      <td><input type="text" id="filter-date" disabled/></td>
      <td style="display: none;"><select  style="width: 150px;"><option value="-"> </option><option value="and">AND</option><option value="or">OR</option></select></td>
    </tr>-->
  </tbody>
</table>