{{wrap file="_include/page.phtml"}}

{{into slot="content_wrapper"}} 
<table>
  <tr>
    <th>Записи nginx error.log</th>
  </tr>
  <tr>
    <td class="debug-row">
      {$#nginx_error|raw}
    </td>
  </tr>
  <tr>
    <th>Записи nginx combine.log</th>
  </tr>
  <tr>
    <td class="debug-row">
      {$#combine_error|raw}
    </td>
  </tr>
  <tr><th>Записи в таблице</th></tr>
  </table>
<div class="debug-tables">  
    {$#tables_rows|raw}
</div>
{{/into}}  

{{ainto slot="js_ready"}}

{{/ainto}}
  
{{/wrap}}
