<ul style="margin-left: 10px;padding: 0;" id="main-view">
  {{list using="$#charts" as="$item"}}
    {{list:item}}
    <li class="chart" id="chart_{$item.id}" style="list-style: none;"></div>
      <div class="chart_graph"></div>      
      <div class="chart-toolbox" onclick="return window.main.showToolbox(this);"></div>
      <div class="toolbox">
        <ul>
          <li onclick="window.chart.changeView(2,{$item.id}); return false;">Линия</li>
          <li onclick="window.chart.changeView(0,{$item.id}); return false;">Сплайн</li>
          <li onclick="window.chart.changeView(3,{$item.id}); return false;">Область</li>
          <li onclick="window.chart.changeView(1,{$item.id}); return false;">Столбцы</li>
          <li onclick="window.chart.exportCSV({$item.id});    return false;">Экспорт CSV</li>
          <li onclick="window.main.deleteChart({$item.id});   return false;">Удалить</li>
        </ul>
      </div>
    </li>
    {{/list:item}}
  {{/list}}  
</ul>


{{ainto slot="js_ready"}}
  window.chart.addEvents();
{{/ainto}}
