{{wrap file="_include/page.phtml"}}
  
{{into slot="menu"}}
  <div id="select-menu">
    <select class="project-selector" onchange="window.main.selectProject(this);return false;">
      {{list using="$#projects" as="$item"}}
        {{list:item}}
          <option value="{$item.id}" {$item.select}>{$item.title}</option>     
        {{/list:item}}
      {{/list}}     
    </select>
  </div>
  <div id="tabs">    
    <ul class='etabs'>
      {{list using="$#tabs" as="$item"}}
        {{list:item}}          
          <li class='tab'><a href="#content" id="{$item.id}" style="text-decoration: none;">{$item.title}</a></li>        
        {{/list:item}}
      {{/list}}     
    </ul>    
  </div>
{{/into}}
{{into slot="content_wrapper"}} 
<center>
<div id="tab-content">
  <div id="content">
    Please Wait for loading...
  </div>
</div>
{{/into}}

  {{ainto slot="js_ready"}}
    $('#tabs').easytabs({
      panelContext:$("#tab-content")
    });
    //window.main.loadMenu({$#tabs|raw},"tabs");
  {{/ainto}}
  
{{/wrap}}