{{wrap file="_include/page.phtml"}}

{{into slot="content_wrapper"}} 
<table id="projects">
  <thead>
    <tr>
      <th>ID</th>
      <th>Название</th>          
    </tr>
  </thead>
  <tbody>
    {{list using="$#projects" as="$item"}}
    {{list:item}}
      <tr>
        <td>{$item.id}</td>
        <td><a href="#" onclick ="window.main.selectProject({$item.id});return false;">{$item.title}</a></td>            
      </tr>
    {{/list:item}}
  {{/list}}     
  </tbody>
</table>
{{/into}}  

{{ainto slot="js_ready"}}
  $('#projects').dataTable();
{{/ainto}}
  
{{/wrap}}