SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE `log_addStock` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` int(10) unsigned NOT NULL DEFAULT '0',
  `ext_id` varchar(150) NOT NULL DEFAULT '',
  `stamp` int(15) NOT NULL DEFAULT '0',
  `event` varchar(50) NOT NULL DEFAULT '',
  `item_id` int(15) NOT NULL DEFAULT '0',
  `value` int(15) NOT NULL DEFAULT '0',
  `level` int(5) unsigned NOT NULL DEFAULT '0',
  `session` int(10) unsigned NOT NULL DEFAULT '0',
  `return` int(10) unsigned NOT NULL DEFAULT '0',
  `energy` int(10) unsigned NOT NULL DEFAULT '0',
  `real` int(10) unsigned NOT NULL DEFAULT '0',
  `bonus` int(10) unsigned NOT NULL DEFAULT '0',
  `money` int(10) unsigned NOT NULL DEFAULT '0',
  `referal` varchar(150) NOT NULL DEFAULT '',
  `reg_time` int(15) unsigned NOT NULL DEFAULT '0',
  `data` varchar(500) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `log_costStock` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` int(10) unsigned NOT NULL DEFAULT '0',
  `ext_id` varchar(150) NOT NULL DEFAULT '',
  `stamp` int(15) NOT NULL DEFAULT '0',
  `event` varchar(50) NOT NULL DEFAULT '',
  `item_id` int(15) NOT NULL DEFAULT '0',
  `value` int(15) NOT NULL DEFAULT '0',
  `level` int(5) unsigned NOT NULL DEFAULT '0',
  `session` int(10) unsigned NOT NULL DEFAULT '0',
  `return` int(10) unsigned NOT NULL DEFAULT '0',
  `energy` int(10) unsigned NOT NULL DEFAULT '0',
  `real` int(10) unsigned NOT NULL DEFAULT '0',
  `bonus` int(10) unsigned NOT NULL DEFAULT '0',
  `money` int(10) unsigned NOT NULL DEFAULT '0',
  `referal` varchar(150) NOT NULL DEFAULT '',
  `reg_time` int(15) unsigned NOT NULL DEFAULT '0',
  `data` varchar(500) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `log_featureUse` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` int(10) unsigned NOT NULL DEFAULT '0',
  `ext_id` varchar(150) NOT NULL DEFAULT '',
  `stamp` int(15) NOT NULL DEFAULT '0',
  `event` varchar(50) NOT NULL DEFAULT '',
  `item_id` int(15) NOT NULL DEFAULT '0',
  `value` int(15) NOT NULL DEFAULT '0',
  `level` int(5) unsigned NOT NULL DEFAULT '0',
  `session` int(10) unsigned NOT NULL DEFAULT '0',
  `return` int(10) unsigned NOT NULL DEFAULT '0',
  `energy` int(10) unsigned NOT NULL DEFAULT '0',
  `real` int(10) unsigned NOT NULL DEFAULT '0',
  `bonus` int(10) unsigned NOT NULL DEFAULT '0',
  `money` int(10) unsigned NOT NULL DEFAULT '0',
  `referal` varchar(150) NOT NULL DEFAULT '',
  `reg_time` int(15) unsigned NOT NULL DEFAULT '0',
  `data` varchar(500) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `log_levelUp` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` int(10) unsigned NOT NULL DEFAULT '0',
  `ext_id` varchar(150) NOT NULL DEFAULT '',
  `stamp` int(15) NOT NULL DEFAULT '0',
  `event` varchar(50) NOT NULL DEFAULT '',
  `item_id` int(15) NOT NULL DEFAULT '0',
  `value` int(15) NOT NULL DEFAULT '0',
  `level` int(5) unsigned NOT NULL DEFAULT '0',
  `session` int(10) unsigned NOT NULL DEFAULT '0',
  `return` int(10) unsigned NOT NULL DEFAULT '0',
  `energy` int(10) unsigned NOT NULL DEFAULT '0',
  `real` int(10) unsigned NOT NULL DEFAULT '0',
  `bonus` int(10) unsigned NOT NULL DEFAULT '0',
  `money` int(10) unsigned NOT NULL DEFAULT '0',
  `referal` varchar(150) NOT NULL DEFAULT '',
  `reg_time` int(15) unsigned NOT NULL DEFAULT '0',
  `data` varchar(500) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `log_Login` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` int(10) unsigned NOT NULL DEFAULT '0',
  `ext_id` varchar(150) NOT NULL DEFAULT '',
  `stamp` int(15) NOT NULL DEFAULT '0',
  `event` varchar(50) NOT NULL DEFAULT '',
  `item_id` int(15) NOT NULL DEFAULT '0',
  `value` int(15) NOT NULL DEFAULT '0',
  `level` int(5) unsigned NOT NULL DEFAULT '0',
  `session` int(10) unsigned NOT NULL DEFAULT '0',
  `return` int(10) unsigned NOT NULL DEFAULT '0',
  `energy` int(10) unsigned NOT NULL DEFAULT '0',
  `real` int(10) unsigned NOT NULL DEFAULT '0',
  `bonus` int(10) unsigned NOT NULL DEFAULT '0',
  `money` int(10) unsigned NOT NULL DEFAULT '0',
  `referal` varchar(150) NOT NULL DEFAULT '',
  `reg_time` int(15) unsigned NOT NULL DEFAULT '0',
  `data` varchar(500) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `log_NewPlayer` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` int(10) unsigned NOT NULL DEFAULT '0',
  `ext_id` varchar(150) NOT NULL DEFAULT '',
  `stamp` int(15) NOT NULL DEFAULT '0',
  `event` varchar(50) NOT NULL DEFAULT '',
  `item_id` int(15) NOT NULL DEFAULT '0',
  `value` int(15) NOT NULL DEFAULT '0',
  `level` int(5) unsigned NOT NULL DEFAULT '0',
  `session` int(10) unsigned NOT NULL DEFAULT '0',
  `return` int(10) unsigned NOT NULL DEFAULT '0',
  `energy` int(10) unsigned NOT NULL DEFAULT '0',
  `real` int(10) unsigned NOT NULL DEFAULT '0',
  `bonus` int(10) unsigned NOT NULL DEFAULT '0',
  `money` int(10) unsigned NOT NULL DEFAULT '0',
  `referal` varchar(150) NOT NULL DEFAULT '',
  `reg_time` int(15) unsigned NOT NULL DEFAULT '0',
  `data` varchar(500) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `log_OutEnergy` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` int(10) unsigned NOT NULL DEFAULT '0',
  `ext_id` varchar(150) NOT NULL DEFAULT '',
  `stamp` int(15) NOT NULL DEFAULT '0',
  `event` varchar(50) NOT NULL DEFAULT '',
  `item_id` int(15) NOT NULL DEFAULT '0',
  `value` int(15) NOT NULL DEFAULT '0',
  `level` int(5) unsigned NOT NULL DEFAULT '0',
  `session` int(10) unsigned NOT NULL DEFAULT '0',
  `return` int(10) unsigned NOT NULL DEFAULT '0',
  `energy` int(10) unsigned NOT NULL DEFAULT '0',
  `real` int(10) unsigned NOT NULL DEFAULT '0',
  `bonus` int(10) unsigned NOT NULL DEFAULT '0',
  `money` int(10) unsigned NOT NULL DEFAULT '0',
  `referal` varchar(150) NOT NULL DEFAULT '',
  `reg_time` int(15) unsigned NOT NULL DEFAULT '0',
  `data` varchar(500) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `log_payCost` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` int(10) unsigned NOT NULL DEFAULT '0',
  `ext_id` varchar(150) NOT NULL DEFAULT '',
  `stamp` int(15) NOT NULL DEFAULT '0',
  `event` varchar(50) NOT NULL DEFAULT '',
  `item_id` int(15) NOT NULL DEFAULT '0',
  `value` int(15) NOT NULL DEFAULT '0',
  `level` int(5) unsigned NOT NULL DEFAULT '0',
  `session` int(10) unsigned NOT NULL DEFAULT '0',
  `return` int(10) unsigned NOT NULL DEFAULT '0',
  `energy` int(10) unsigned NOT NULL DEFAULT '0',
  `real` int(10) unsigned NOT NULL DEFAULT '0',
  `bonus` int(10) unsigned NOT NULL DEFAULT '0',
  `money` int(10) unsigned NOT NULL DEFAULT '0',
  `referal` varchar(150) NOT NULL DEFAULT '',
  `reg_time` int(15) unsigned NOT NULL DEFAULT '0',
  `data` varchar(500) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `log_QuestDone` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` int(10) unsigned NOT NULL DEFAULT '0',
  `ext_id` varchar(150) NOT NULL DEFAULT '',
  `stamp` int(15) NOT NULL DEFAULT '0',
  `event` varchar(50) NOT NULL DEFAULT '',
  `item_id` int(15) NOT NULL DEFAULT '0',
  `value` int(15) NOT NULL DEFAULT '0',
  `level` int(5) unsigned NOT NULL DEFAULT '0',
  `session` int(10) unsigned NOT NULL DEFAULT '0',
  `return` int(10) unsigned NOT NULL DEFAULT '0',
  `energy` int(10) unsigned NOT NULL DEFAULT '0',
  `real` int(10) unsigned NOT NULL DEFAULT '0',
  `bonus` int(10) unsigned NOT NULL DEFAULT '0',
  `money` int(10) unsigned NOT NULL DEFAULT '0',
  `referal` varchar(150) NOT NULL DEFAULT '',
  `reg_time` int(15) unsigned NOT NULL DEFAULT '0',
  `data` varchar(500) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `log_QuestStart` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` int(10) unsigned NOT NULL DEFAULT '0',
  `ext_id` varchar(150) NOT NULL DEFAULT '',
  `stamp` int(15) NOT NULL DEFAULT '0',
  `event` varchar(50) NOT NULL DEFAULT '',
  `item_id` int(15) NOT NULL DEFAULT '0',
  `value` int(15) NOT NULL DEFAULT '0',
  `level` int(5) unsigned NOT NULL DEFAULT '0',
  `session` int(10) unsigned NOT NULL DEFAULT '0',
  `return` int(10) unsigned NOT NULL DEFAULT '0',
  `energy` int(10) unsigned NOT NULL DEFAULT '0',
  `real` int(10) unsigned NOT NULL DEFAULT '0',
  `bonus` int(10) unsigned NOT NULL DEFAULT '0',
  `money` int(10) unsigned NOT NULL DEFAULT '0',
  `referal` varchar(150) NOT NULL DEFAULT '',
  `reg_time` int(15) unsigned NOT NULL DEFAULT '0',
  `data` varchar(500) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `log_QuestTaskComplete` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` int(10) unsigned NOT NULL DEFAULT '0',
  `ext_id` varchar(150) NOT NULL DEFAULT '',
  `stamp` int(15) NOT NULL DEFAULT '0',
  `event` varchar(50) NOT NULL DEFAULT '',
  `item_id` int(15) NOT NULL DEFAULT '0',
  `value` int(15) NOT NULL DEFAULT '0',
  `level` int(5) unsigned NOT NULL DEFAULT '0',
  `session` int(10) unsigned NOT NULL DEFAULT '0',
  `return` int(10) unsigned NOT NULL DEFAULT '0',
  `energy` int(10) unsigned NOT NULL DEFAULT '0',
  `real` int(10) unsigned NOT NULL DEFAULT '0',
  `bonus` int(10) unsigned NOT NULL DEFAULT '0',
  `money` int(10) unsigned NOT NULL DEFAULT '0',
  `referal` varchar(150) NOT NULL DEFAULT '',
  `reg_time` int(15) unsigned NOT NULL DEFAULT '0',
  `data` varchar(500) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `log_viralRecive` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` int(10) unsigned NOT NULL DEFAULT '0',
  `ext_id` varchar(150) NOT NULL DEFAULT '',
  `stamp` int(15) NOT NULL DEFAULT '0',
  `event` varchar(50) NOT NULL DEFAULT '',
  `item_id` int(15) NOT NULL DEFAULT '0',
  `value` int(15) NOT NULL DEFAULT '0',
  `level` int(5) unsigned NOT NULL DEFAULT '0',
  `session` int(10) unsigned NOT NULL DEFAULT '0',
  `return` int(10) unsigned NOT NULL DEFAULT '0',
  `energy` int(10) unsigned NOT NULL DEFAULT '0',
  `real` int(10) unsigned NOT NULL DEFAULT '0',
  `bonus` int(10) unsigned NOT NULL DEFAULT '0',
  `money` int(10) unsigned NOT NULL DEFAULT '0',
  `referal` varchar(150) NOT NULL DEFAULT '',
  `reg_time` int(15) unsigned NOT NULL DEFAULT '0',
  `data` varchar(500) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `log_viralSend` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `project_id` int(10) unsigned NOT NULL DEFAULT '0',
  `ext_id` varchar(150) NOT NULL DEFAULT '',
  `stamp` int(15) NOT NULL DEFAULT '0',
  `event` varchar(50) NOT NULL DEFAULT '',
  `item_id` int(15) NOT NULL DEFAULT '0',
  `value` int(15) NOT NULL DEFAULT '0',
  `level` int(5) unsigned NOT NULL DEFAULT '0',
  `session` int(10) unsigned NOT NULL DEFAULT '0',
  `return` int(10) unsigned NOT NULL DEFAULT '0',
  `energy` int(10) unsigned NOT NULL DEFAULT '0',
  `real` int(10) unsigned NOT NULL DEFAULT '0',
  `bonus` int(10) unsigned NOT NULL DEFAULT '0',
  `money` int(10) unsigned NOT NULL DEFAULT '0',
  `referal` varchar(150) NOT NULL DEFAULT '',
  `reg_time` int(15) unsigned NOT NULL DEFAULT '0',
  `data` varchar(500) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS = 1;
