SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE `log_NewPlayer` ADD COLUMN `sex` INT(1) UNSIGNED NULL DEFAULT 0  AFTER `data` , ADD COLUMN `age` INT(3) UNSIGNED NULL DEFAULT 0  AFTER `sex` , ADD COLUMN `fb_source` VARCHAR(45) NULL DEFAULT ''  AFTER `age` , ADD COLUMN `country` VARCHAR(45) NULL DEFAULT ''  AFTER `fb_source` ;
ALTER TABLE `log_Login` ADD COLUMN `sex` INT(1) UNSIGNED NULL DEFAULT 0  AFTER `data` , ADD COLUMN `age` INT(3) UNSIGNED NULL DEFAULT 0  AFTER `sex` , ADD COLUMN `fb_source` VARCHAR(45) NULL DEFAULT ''  AFTER `age` , ADD COLUMN `country` VARCHAR(45) NULL DEFAULT ''  AFTER `fb_source` ;
ALTER TABLE `log_featureUse` ADD COLUMN `pack` VARCHAR(45) NULL DEFAULT ''  AFTER `data` , ADD COLUMN `name` VARCHAR(45) NULL DEFAULT ''  AFTER `pack` ;
ALTER TABLE `log_payCost` ADD COLUMN `pack` VARCHAR(45) NULL DEFAULT ''  AFTER `data` , ADD COLUMN `name` VARCHAR(45) NULL DEFAULT ''  AFTER `pack`, ADD COLUMN `currencyName` VARCHAR(45) AFTER `name`;
ALTER TABLE `log_viralSend` ADD COLUMN `type` VARCHAR(45) NULL DEFAULT ''  AFTER `data` , ADD COLUMN `name` VARCHAR(45) NULL DEFAULT ''  AFTER `type` ;
ALTER TABLE `log_viralRecive` ADD COLUMN `type` VARCHAR(45) NULL DEFAULT ''  AFTER `data` , ADD COLUMN `name` VARCHAR(45) NULL DEFAULT ''  AFTER `type` ;

SET FOREIGN_KEY_CHECKS = 1;