{{wrap file="_include/page.phtml"}}

{{into slot="content_wrapper"}} 
<h1>{$#title}</h1>
<ul class="breadcrumb">
  <li><a href="/">Projects</a> <span class="divider">/</span></li>
  <li class="active">{$#title}</li>  
</ul>

<ul class="nav nav-tabs">
  {{list using="$#pages" as="$item"}}
    {{list:item}}
      <li><a id="navTab{$item.id}" onclick="return window.main.loadPage({$item.id});" href="#">{$item.name}</a></li>        
    {{/list:item}}
  {{/list}}     
</ul>

<div id="workspace">
  <div id = "chart-header">
    <div class="btn-group-setting">
      <a class="btn dropdown-toggle" id ="settings-group" data-toggle="dropdown" data-target="#">
        Управление
      <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li><a href="#" onclick="return window.chart.addChartClick();">Добавить диаграмму</a></li>
        <li><a href="#" onclick="return window.main.addTab();">Добавить страницу</a></li>
        <li><a href="#" onclick="return window.main.renameTab();">Переименовать страницу</a></li>
        <li><a href="#" onclick="return window.main.deleteTab();">Удалить страницу</a></li>
      </ul>
    </div>
    
  </div>
  
  <div id = "chartspace">
    
  </div>
</div>

{{/into}}  

{{ainto slot="js_ready"}}
  $('btn dropdown-toggle').dropdown();
  window.main.loadPage({$#active_id});
{{/ainto}}

{{/wrap}}